#!/bin/bash
# MCP Server Startup Script for weather_openmeteo
# Generated by CoachArtie MCP Installer

set -e

echo "🚀 Starting weather_openmeteo MCP Server..."

# Load environment variables
if [ -f .env ]; then
    export $(cat .env | grep -v ^# | xargs)
    echo "✅ Environment variables loaded"
else
    echo "⚠️  No .env file found. Using system environment."
fi

# Check required environment variables


# Start the MCP server
echo "🌟 Starting MCP server on port 3005..."
exec node node_modules/@rehmatalisayany/weather-mcp-server/dist/index.js
