/**
 * Memory-oriented context source builders extracted verbatim from ContextAlchemy.
 *
 * Behavior is byte-for-byte identical to the original private methods — the only
 * change is that instance state (`this.memoryEntourage`) is now passed in as an
 * explicit parameter so these live as plain functions. Do not change wording,
 * priorities, token weights, thresholds, or ordering.
 */

import { logger } from '@coachartie/shared';
import { estimateTokens } from '@coachartie/shared';
import type { IncomingMessage } from '@coachartie/shared';
import type { MemoryEntourageInterface } from '../../memory/memory-entourage-interface.js';
import type { ContextSource } from '../context-providers/types.js';
import { DEBUG } from '../context-providers/types.js';
import {
  formatLearnedRulesForContext,
  extractParticipants,
} from './transcript-helpers.js';

/**
 * Yard historian — occasionally surface ONE notable past moment as an OPTIONAL callback,
 * so the community feels remembered. Low priority + "only if it fits" framing: Artie weaves
 * it in as a "remember when..." when it's relevant and ignores it otherwise. It's a callback,
 * not a history lesson. Rate: YARD_CALLBACK_CHANCE (default 0.2), guild channels only.
 */
export async function addYardCallback(
  message: IncomingMessage,
  sources: ContextSource[]
): Promise<void> {
  try {
    const guildId = message.context?.guildId;
    if (!guildId) return;
    const chance = parseFloat(process.env.YARD_CALLBACK_CHANCE || '0.2');
    if (!(chance > 0) || Math.random() > chance) return;

    const { getSyncDb } = await import('@coachartie/shared');
    const db = getSyncDb();
    // A notable moment from a while back — not the last few days (those are still fresh in
    // the transcript). High-importance, guild-scoped, older than 5 days, picked at random.
    const row = db.get<{ content: string; created_at: string }>(
      `SELECT content, created_at FROM memories
       WHERE guild_id = ? AND importance >= 7
         AND created_at < datetime('now', '-5 days')
       ORDER BY RANDOM() LIMIT 1`,
      [guildId]
    );
    if (!row?.content) return;

    // Drop any "[Observation from ...] " prefix for readability.
    const bracketEnd = row.content.indexOf('] ');
    const body = (bracketEnd > 0 ? row.content.slice(bracketEnd + 2) : row.content).slice(0, 400);
    const when = row.created_at?.slice(0, 10) || 'a while back';

    const content =
      `📅 CALLBACK (optional): a real thing that happened in this server on ${when} — "${body}". ` +
      `If it fits the moment, drop it as a "remember when..." callback; if it doesn't fit, ignore ` +
      `it completely. Never force a history lesson or read it out cold.`;

    sources.push({
      name: 'yard_callback',
      priority: 40,
      tokenWeight: estimateTokens(content),
      content,
      category: 'memory',
    });
    if (DEBUG) logger.info(`│ 📅 Yard callback injected (${when})`);
  } catch (e) {
    logger.warn('Yard callback failed:', e);
  }
}

/**
 * Add learned rules - consolidated actionable rules from feedback patterns
 * These are persistent rules generated by the reflection consolidator service
 * Priority 92: high, after temporal but before capabilities
 */
export async function addLearnedRules(
  message: IncomingMessage,
  sources: ContextSource[]
): Promise<void> {
  try {
    const guildId = message.context?.guildId;

    // Import the reflection consolidator
    const { reflectionConsolidator } = await import('../../learning/reflection-consolidator.js');

    // Get system-wide rules (always apply)
    const systemRules = await reflectionConsolidator.getActiveRules('system');

    // Get guild-specific rules if in a guild context
    const guildRules = guildId
      ? await reflectionConsolidator.getActiveRules('guild', guildId)
      : [];

    const allRules = [...systemRules, ...guildRules];

    if (allRules.length === 0) {
      if (DEBUG) {
        logger.info('│ ⚪ No learned rules to inject');
      }
      return;
    }

    // Format rules for context injection
    const rulesContent = formatLearnedRulesForContext(allRules, guildId);

    sources.push({
      name: 'learned_rules',
      priority: 92, // High priority - these are important behavioral guidelines
      tokenWeight: estimateTokens(rulesContent),
      content: rulesContent,
      category: 'system',
    });

    if (DEBUG) {
      logger.info(
        `│ ✅ Injected ${allRules.length} learned rules (${systemRules.length} system, ${guildRules.length} guild)`
      );
    }
  } catch (error) {
    logger.warn('Failed to add learned rules:', error);
    // Graceful degradation - continue without learned rules
  }
}

/**
 * Add relevant memories to message context (matches assembleMessagePreamble pattern)
 */
export async function addRelevantMemories(
  message: IncomingMessage,
  sources: ContextSource[],
  capabilityContext: string[] | undefined,
  memoryEntourage: MemoryEntourageInterface
): Promise<void> {
  try {
    // Enhance search query with capability context for tool-specific memories
    let searchQuery = message.message;
    if (capabilityContext && capabilityContext.length > 0) {
      const capabilityHints = capabilityContext.join(' ');
      searchQuery = `${message.message} [capabilities: ${capabilityHints}]`;
      if (DEBUG) {
        logger.info(`🔧 Enhanced memory search with capability context: ${capabilityHints}`);
      }
    }

    // Enrich the query with WHO is actually in this conversation. Memory recall is
    // TF-IDF over the query text — so "rank the crew" or "who's been up to what" can't
    // match a memory about a specific person by name, and the recall comes back empty
    // (why his rankings were just recaps of the last 20 messages). Appending the active
    // participants' names/handles makes recall pull each person's real history. The
    // relevance threshold keeps this from polluting non-people questions: a metro-cost
    // query won't clear threshold on a person-memory just because a name rode along.
    const participants = extractParticipants(message);
    // Distinctive name tokens for scoring (jan_gbg, legalmexicanalien, yellowaquarium).
    // These let the recaller pull in AND rank up memories that mention the people
    // actually present — the query-text append alone was too weak a signal to beat
    // generic memories, so "rank the crew" surfaced whoever was most recent, not who's here.
    const participantTokens = Array.from(
      new Set(
        participants
          .flatMap((p) => p.toLowerCase().split(/[^a-z0-9_]+/))
          .filter((t) => t.length >= 4)
      )
    );
    if (participants.length > 0) {
      searchQuery = `${searchQuery} [people here: ${participants.join(', ')}]`;
    }

    // Calculate available token budget for memory context
    const contextSize = parseInt(process.env.CONTEXT_WINDOW_SIZE || '32000', 10);
    const maxTokensForMemory = Math.max(800, Math.floor(contextSize * 0.15)); // Minimum 800, scales with context

    const startTime = Date.now();
    const memoryResult = await memoryEntourage.getMemoryContext(
      searchQuery,
      message.userId,
      {
        maxTokens: maxTokensForMemory,
        priority: 'speed', // Default to speed for responsive interactions
        minimal: false,
        guildId: message.context?.guildId, // Include guild-scoped memories when in a guild
        participants: participantTokens, // Person-aware recall: rank up who's here
      }
    );
    const searchTime = Date.now() - startTime;

    // Only add memory context if we actually have useful content
    if (memoryResult.content && memoryResult.content.trim().length > 0) {
      sources.push({
        name: 'memory_context',
        priority: 70,
        tokenWeight: estimateTokens(memoryResult.content),
        content: memoryResult.content,
        category: 'memory',
      });

      if (DEBUG) {
        logger.info(
          `🧠 Memory search: ${memoryResult.memoryCount} memories found in ${searchTime}ms (confidence:${(memoryResult.confidence * 100).toFixed(1)}%, categories:${memoryResult.categories.join(',')})`
        );
      }
    } else {
      if (DEBUG) {
        logger.info('🧠 Memory search: no relevant memories found');
      }
    }
  } catch (error) {
    logger.warn('Failed to add relevant memories:', error);
    // Graceful degradation - continue without memory context
  }
}
