#!/bin/bash
# MCP Server Startup Script for brave_search
# Generated by CoachArtie MCP Installer

set -e

echo "🚀 Starting brave_search MCP Server..."

# Load environment variables
if [ -f .env ]; then
    export $(cat .env | grep -v ^# | xargs)
    echo "✅ Environment variables loaded"
else
    echo "⚠️  No .env file found. Using system environment."
fi

# Check required environment variables

if [ -z "$BRAVE_API_KEY" ]; then
    echo "❌ Missing required environment variable: BRAVE_API_KEY"
    exit 1
fi

# Start the MCP server
echo "🌟 Starting MCP server on port 3009..."
exec node node_modules/@modelcontextprotocol/server-brave-search/dist/index.js
