#!/bin/bash
# MCP Server Startup Script for filesystem
# Generated by CoachArtie MCP Installer

set -e

echo "🚀 Starting filesystem MCP Server..."

# Load environment variables
if [ -f .env ]; then
    export $(cat .env | grep -v ^# | xargs)
    echo "✅ Environment variables loaded"
else
    echo "⚠️  No .env file found. Using system environment."
fi

# Check required environment variables


# Start the MCP server
echo "🌟 Starting MCP server on port 3003..."
exec node node_modules/@modelcontextprotocol/server-filesystem/dist/index.js
